export const THEME_FIELDS = [
  { key: "mainHeaderBg", label: "Main Header Background" },
  { key: "headerBg", label: "Header Background" },
  { key: "headerTopBg", label: "Header Top Bg" },
  { key: "btnBg", label: "Button Background" },
  { key: "btnHoverBg", label: "Button Hover Color" },
  { key: "iconColor", label: "Icon Color" },
  { key: "cardBg", label: "Card Background" },
  { key: "headerSocialIconbg", label: "Header Icon Background" },
  { key: "headerSocialIconHover", label: "Header Icon Color" },
  { key: "themeColorLight", label: "Light Color" },
  { key: "themeBgLight", label: "Background Color" },
  { key: "themeNoticeBgColor", label: "Notice Header Color" },
  { key: "themeNoticeTextColor", label: "Notice Header Text Color" },
  { key: "bodyTextColor", label: "Body Text Color" },
  { key: "colorWhite", label: "White Color" },
  { key: "colorDark", label: "Dark Color" },
  { key: "heroOverlayColor", label: "Hero Overlay Color" },
  { key: "footerBg", label: "Footer Background" },
  { key: "themeColor", label: "Primary Color" },
  { key: "themeColor2", label: "Secondary Color" },
  // { key: "footerBg2", label: "Footer Secondary Background" },
  { key: "footerTextColor", label: "Footer Text Color" },
];
